version_info: '0'
resources:
  - '@type': type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
    cluster_name: echo_service
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address: { address: 192.168.2.244, port_value: 5000 }
