apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  template:
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:latest
          command:
            - envoy
          args:
            - '-c /etc/envoy/envoy.yaml'
            - '--service-node front'
            - '--service-cluster front'
            - '-l $(ENVOY_LOG_LEVEL)'
          env:
            - name: ENVOY_LOG_LEVEL
              value: debug
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
            - name: envoy-certs
              mountPath: /etc/envoy
            readOnly: true
          readinessProbe:
            httpGet:
              path: /server_info
              port: 9901
          livenessProbe:
            httpGet:
              path: /server_info
              port: 9901
          ports:
            - name: envoy-admin
              containerPort: 9901
            - name: http
              containerPort: 9090
            - name: https
              containerPort: 9443
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: envoy-certs
          secret:
            secretName: envoy-certs
