apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
namespace: production
namePrefix: prod-
nameSuffix: -v1

commonLabels:
  environment: development
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am production!

resources:
   - ../../base

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/resource_limit.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  - name: env-vars
#  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - LOG_LEVEL=info
      - ENVOY_LOG_LEVEL=error

secretGenerator:
  - name: postgres-secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=e2e-real-pass
  - name: certs
    behavior: replace
    files:
      - secrets/certs/ca-cert.pem
      - secrets/certs/server-cert.pem
      - secrets/certs/server-key.pem
      - secrets/certs/upstream-ca-cert.pem
      - secrets/certs/upstream-cert.pem
      - secrets/certs/upstream-key.pem
    type: Opaque

# labels for generated secrets at this level
#generatorOptions:
#  disableNameSuffixHash: true

replicas:
  - name: postgres
    count: 1

images:
  - name: etcd
    newTag: 3.3.15
  - name: postgres
    newTag: 11.9-alpine
  - name: envoyproxy/envoy-alpine
    newName: docker.io/envoyproxy/envoy-alpine
    newTag: v1.15.2
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v2.9.3
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/recorder-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/recorder-srv
    newTag: $(IMAGE_VERSION)
