apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/instance: postgres-abcxzy
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: yeti
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

resources:
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml

secretGenerator:
  - name: postgres-secrets
    literals:
      - postgres-password=postgres123

vars:
  - name: DATABASE_ENDPOINT
    objref:
      kind: Service
      name: postgres
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
