node:
  id: id
  cluster: cluster

admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

dynamic_resources:
  cds_config:
    path: '/etc/envoy/clusters.yaml'
  lds_config:
    path: '/etc/envoy/listeners.yaml'
